application: wechat-callapi
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: res/favicon.png
  upload: res/favicon.png

- url: /robots.txt
  static_files: res/robots.txt
  upload: res/robots.txt  

- url: /images/(.*\.(gif|png|jpg))
  static_files: res/img/\1
  upload: res/img/(.*\.(gif|png|jpg))
  
- url: /css/(.*\.(css))
  static_files: res/css/\1
  upload: res/css/(.*\.(css))  

- url: /.*
  script: main.app
  
libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.1.1"